int testaData(int, int, int);
int bissexto(int);
int testaHora(int, int);
int testaNome(char nome[]);
int testaCPF(char*);
int validaOpcao(char);
int memoriaAlocada(void);
int testaTitulo(char*);
int testaISBN(char*);
int testaDataNasc(char*);
void validaMenu(void);